ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.increment-decrement]
[rule.var-declaration]
#[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.unnecessary-stmt]
[rule.duplicated-imports]
[rule.empty-lines]
[rule.atomic]
[rule.range-val-address]
[rule.bool-literal-in-expr]
[rule.constant-logical-expr]
[rule.modifies-value-receiver]
#[rule.add-constant]
#arguments = [{ maxLitCount = "3", allowStrs ="\"%s%s\",\"\"", allowInts="0,1,2,3,4,5", allowFloats="0.0,0.,.0,1.,1.0" }]
[rule.confusing-results]
[rule.modifies-parameter]
[rule.get-return]
[rule.confusing-naming]
[rule.string-of-int]
